chain_partition_args:
  bilinear_max_len: 50
  bilinear_partition_weight: 0
  identity_partition_weight: 0
  linear_n_classes:
  - 2
  - 2
  linear_partition_weight: 0
  partition_min_frac: 0
  partition_min_len: 10
esm_args:
  esm_gpu_idx: 0
  esm_msa_dir: null
  max_msa_seqs: 128
  use_esm_1b: false
  use_esm_both_chain_prob: 0
  use_esm_msa: false
  use_esm_prob: 0
feat_gen_args:
  mask_feat_n_seq_indep_prob: 0
  mask_feats: false
  mask_seq: true
feature_args:
  bb_dihedral_embed_dim: -1
  bb_dihedral_encode_dim: 24
  centrality_embed_dim: -1
  centrality_encode_dim: 6
  embed_bb_dihedral: false
  embed_centrality: false
  embed_rel_dist: false
  embed_rel_sep: false
  embed_res_rel_pos: false
  embed_res_ty: false
  embed_sec_struct: false
  embed_tr_rosetta_ori: false
  encode_local_rel_coords: false
  fourier_encode_bb_dihedral: false
  fourier_encode_tr_rosetta_ori: false
  include_sc_dihedral: false # not used
  sc_dihedral_encode_dim: 24 # added
  joint_embed_res_pair_rel_sep: true
  joint_embed_res_pair_rel_sep_embed_dim: 60
  one_hot_bb_dihedral: true
  one_hot_centrality: false
  one_hot_rel_chain: true
  one_hot_rel_dist: false
  one_hot_rel_sep: false
  one_hot_res_rel_pos: true
  one_hot_res_ty: true
  one_hot_tr_rosetta_ori: true
  quat_encode_rel_ori: false
  rbf_encode_centrality: true
  rbf_encode_rel_distance: true
  rel_dist_atom_tys:
  - CA
  - CA
  - CA
  - N
  - CA
  - C
  - CA
  - CB
  - N # added
  - O # added
  rel_dist_bounds:
  - 2.0
  - 16.0
  rel_dist_embed_dim: -1
  rel_dist_encode_dim: 18
  rel_sep_embed_dim: -1
  res_rel_pos_embed_dim: -1
  res_rel_pos_encode_dim: 10
  res_ty_corrupt_prob: 0.0
  res_ty_embed_dim: -1
  sc_dihedral_noise:
  - 0
  - 0
  sec_struct_embed_dim: 0
  tr_rosetta_ori_embed_dim: -1
  tr_rosetta_ori_encode_dim: 24
flag_args:
  cdr_interface: false
  contact_fracs:
  - 0
  - 0
  contact_thresh: 0
  include_block_adjs: false
  include_bond_flags: false
  include_both_interface_prob: 0
  include_complex_flags: false
  include_contact_prob: 0
  include_interface_prob: 0
  include_ss_one_hot: false
  include_terminal_flags: false
  interface_fracs: 0
  num_contact: null
  num_interface: null
  random_contact: null
  random_interface: null
gt_args:
  depth:
  - 6
  - 4
  do_pair_outer:
  - 1
  - 0
  do_tri_attn:
  - 1
  - 0
  do_tri_mul:
  - 1
  - 0
  node_dim_query:
  - 32
  - 16
  node_dim_query_point:
  - 4
  - 4
  node_dim_value:
  - 32
  - 16
  node_dim_value_point:
  - 8
  - 8
  node_dropout:
  - 0.1
  - 0.1
  node_heads:
  - 8
  - 10
  pair_dim_head:
  - 32
  - 32
  pair_dropout:
  - 0.2
  - 0.0
  pair_heads:
  - 4
  - 4
  scale_rigid_update: false
  share_weights:
  - 0
  - 1
  use_dist_attn:
  - 1
  - 1
  use_ipa:
  - 0
  - 1
inter_chain_mask_args:
  inter_full_mask_weight: 0
  inter_no_mask_weight: 1.0
  inter_one_to_all_mask_weight: 0
  inter_random_mask_weight: 0
intra_chain_mask_args:
  cdr_mask_weight: 0
  contiguous_mask_max_len: 60
  contiguous_mask_min_len: 5
  contiguous_mask_weight: 0
  full_mask_weight: 0
  interface_full_mask_weight: 0
  interface_mask_max_frac: 0
  interface_mask_min_frac: 0
  interface_mask_weight: 0
  inverse_interface_full_mask_weight: 0
  inverse_interface_mask_max_frac: 0
  inverse_interface_mask_min_frac: 0
  inverse_interface_mask_weight: 0
  max_mask_frac: 0.3
  min_mask_frac: 0
  no_mask_weight: 1.0
  random_mask_max_p: 60
  random_mask_min_p: 5
  random_mask_weight: 0
  spatial_mask_max_radius: 12.0
  spatial_mask_top_k: 30
  spatial_mask_weight: 0
  true_interface_mask_weight: 0
  true_inverse_interface_mask_weight: 0
loss_args:
  bond_angle_wt: 3
  bond_len_wt: 1
  com_wt: null
  dist_inv_atom_tys: null
  dist_inv_wt: null
  fape_atom_tys: null
  fape_wt: null
  include_nsr_after: 0
  include_pae_after: 0
  include_plddt_after: 0
  include_viol_after: -1
  inter_fape_scale: null
  mask_rel_wt: 1
  nsr_wt: null
  pae_atom_tys: null
  pae_max_dist: 16
  pae_step: 0.5
  pae_wt: null
  pair_dist_atom_tys:
  - CA
  - CB
  - CA
  - CG
  - CA
  - OG
  - CA
  - OG1
  - CA
  - CG1
  - CA
  - SG
  - CA
  - CG2
  pair_dist_max_dist: 16.0
  pair_dist_step: 0.25
  pair_dist_wt: 0.1
  plddt_atom_tys:
  - distal
  plddt_bins: 25
  plddt_wt: 0.25
  res_fape_wt: null
  sc_rmsd_p: 1
  sc_rmsd_wt: 1.75
  tm_atom_tys:
  - CA
  tm_wt: 0.0
  vdw_wt: 1
  viol_schedule: null
  violation_wt: null
optional arguments:
  coord_noise: 0.0
  help: null
  include_init_rigids: false
  min_len_cutoff: 60
  n_cycles: 1
  node_dim_hidden: 256
  pair_dim_hidden: 128
  partition_chains: false
  predict_bb: false
  predict_from_angles: false
  predict_sc_atoms: true
  torsion_loss_weight: 0.5
  train_on_bounded_complex: false
  use_tfn: true
positional arguments:
  model_config: none
se3_args:
  append_edge_attn: false
  append_norm: true
  append_rel_dist: true
  fiber_hidden:
  - 200
  - 16
  fiber_in:
  - 256
  - 3
  fiber_out:
  - 256
  - 37
  learn_head_weights: true
  se3_depth: 6
  se3_dim_heads:
  - 16
  - 4
  se3_edge_dim: 128
  se3_heads:
  - 12
  - 12
